# Generated by Django 5.2.3 on 2025-07-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deadline',
            field=models.DateField(default=2014),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
