# Generated by Django 5.2.4 on 2025-07-28 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_request_deadline_alter_request_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
